// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MM3x-3n5Kh1T7DhW9TUTYPEeudF5jiA',
    appId: '1:1062676055284:web:c9c1a52cee537810624aa1',
    messagingSenderId: '1062676055284',
    projectId: 'rockvin-33f7e',
    authDomain: 'rockvin-33f7e.firebaseapp.com',
    storageBucket: 'rockvin-33f7e.appspot.com',
    measurementId: 'G-RH8ZMRRKPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxfVXhYjZ08rfU9LKor0n9_BEFABdDD8s',
    appId: '1:1062676055284:android:d7a4e0b83eff4523624aa1',
    messagingSenderId: '1062676055284',
    projectId: 'rockvin-33f7e',
    storageBucket: 'rockvin-33f7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBye3nBWg31X3ydeoMMjDtumEaEkqI1ePA',
    appId: '1:1062676055284:ios:d7c7868aa8282de1624aa1',
    messagingSenderId: '1062676055284',
    projectId: 'rockvin-33f7e',
    storageBucket: 'rockvin-33f7e.appspot.com',
    iosClientId: '1062676055284-8jhmvmngkuhdslld1hvp90555ni6d37l.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBye3nBWg31X3ydeoMMjDtumEaEkqI1ePA',
    appId: '1:1062676055284:ios:efeb198952928b5e624aa1',
    messagingSenderId: '1062676055284',
    projectId: 'rockvin-33f7e',
    storageBucket: 'rockvin-33f7e.appspot.com',
    iosClientId: '1062676055284-g9stedglt85btoo1slsh20jnt0g36t6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockvinCafeMobileApplication',
  );
}
